---
output: github_document
always_allow_html: true
---

# chcRne 
The chcRne package was developed to organize functions, useful code snippets, and other information relevant to the Research and Evaluation team at the Center for Healthy Communities.

### Data Management
Functions in this section are used used for data management.

- `pnta.unanswered.to.miss()` Sets all options (vars) in select all that apply questions to NA when the "Prefer not to answer" option was selected.

### Statistics (often used in inline code)
Functions in this section return statistics that are often used for expalnations on figures. Many of these functions will often be used in inline code.

- `count_and_percent` Returns a string tha includes the total count and percentage of the categories in the input variable.


### Visualization
Functions in this section are used for the creation of figures, tables, and other visualizations.

- `nperc_tbl_MATA()` Creates a table showing the n counts and percentages for each option in a mark all that apply question.

Link to package description:

## How to install:

```
install.packages("devtools") 
devtools::install_github("Smoorad99/chcRnePackage")
```


## Examples

```{r table1, include = TRUE}
library(chcRne)

cols <- c("no_goingout_cooking", "no_goingout_broke")
rnames <- c("I like cooking", "I am a broke college student")

# Create table that reports n count and percent for a mark all that apply question
table1 <- nperc_tbl_MATA(df = exp.data,
               vars = cols,
               value = "1",
               row.names = rnames,
               punc = ".",
               col.title = "Why not go out to eat?")
table1
```



