---
output: rmarkdown::html_vignette
title: "Code examples"
pkgdown:
  as_is: true
description: >
  If you are new to chcRne or are blanking on function names you can find documentation on the functions including  examples here.

vignette: >
  %\VignetteIndexEntry{Code examples}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  warning = FALSE,
  message = FALSE,
  comment = "#>"
)
```

```{r setup}
# Load in necessary libraries
library(chcRne)
library(dplyr)
```

This page is currently under development and will contain commonly used code examples that are not suited to a single-function format.

### Applying `remove.na.levels()` to multiple variables

```{r eval=FALSE}
# List out all variable names with this problem
cols.with.na.lvls <- bns2_pkg_data |> 
  select(where(is.ordered)) |> names()

# Apply function
df <- bns2_pkg_data %>% mutate(across(all_of(cols.with.na.lvls), ~remove.na.levels(.x)))
```






