

#' plot_frq y.offset function
#'
#' The sole purpose of `y.off()` is to make sure the count and percent above each bar generated by the `plot_frq` remains "on screen".
#'
#' @param datavar Data frame $ variable
#'
#' @return A `plot_frq` bar chart with counts and percents on screen.
#' @importFrom sjPlot plot_frq
#' @export
#'
#' @examples
#' plot_frq(bns2_pkg_data$q13)
#' plot_frq(bns2_pkg_data$q13, y.offset = y.off(bns2_pkg_data$q13))
#'
#'
#'
y.off <- function(datavar) {
  rows <- max(table(datavar)) # Get the category with the most responses
  if (rows < 6) {
    return(.02)
  }
  else if (rows > 6 & rows <= 20) {
    return(.1)
  }
  else if (rows > 20 & rows <= 50) {
    return(.3)
  }
  else if (rows > 50 & rows <= 100) {
    return(.5)
  }
  else if (rows > 100) {
    return(1)
  }
}
